### ISSUE TITLE
[PE-D] Command Summary table

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-4/tp#253]
![image.png](https://raw.githubusercontent.com/kwokieee/ped/main/files/1db6194c-0fe1-4068-9ddb-4d07ef512d12.png)

Would be good if there was a way to merge the cells so that you can better show that these commands are grouped by specific functionality. Personally, I thought the table was incomplete for a few seconds until I realised that the first column was stating the categories of the commands.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: kwokieee/ped#10

**Comment by hsiaotingluv** [comment]
unfortunately this is not that simple to achieve, it requires usage of external library or recoding the entire table using html
