### ISSUE TITLE
[Nationality] Not Ideal Suggestions with White Spaces

### ISSUE THREAD

**Issue by choonyongchan** [AY2122S1-CS2103T-W08-4/tp#274]
![image](https://user-images.githubusercontent.com/43673767/140065540-58e3c88b-9b6a-49e0-a38c-31f077aaf81a.png)
As seen in the image, there are many suggestions but they are not linked to 'singa pore'. Perhaps we can relook at the code for suggesting nationality/doing away with it, just for nationality

**Comment by kevinmingtarja** [comment]
Should be fixed by #266 !
![Screen Shot 2021-11-04 at 01 20 09](https://user-images.githubusercontent.com/69668484/140146474-efc2de55-5bd7-4b71-99f5-7abf706d400e.png)
