### ISSUE TITLE
[PE-D2] Help command message format error

### ISSUE THREAD

**Issue by hsiaotingluv** [AY2122S1-CS2103T-W08-4/tp#291]
<img width="741" alt="Screenshot 2021-11-05 at 7 00 20 PM" src="https://user-images.githubusercontent.com/68311371/140500559-07cc4155-d75c-46be-a15a-c5f2bd8e490d.png">

**Comment by bklimey** [comment]
Adding on to `help` related issue:

Perhaps `Quit program`?
![image](https://user-images.githubusercontent.com/79616664/140500714-1957d8bf-3b44-41ee-90a8-61a6bf42d5fc.png)

Would be nice to standardize the parameter format to the one on UG
![image](https://user-images.githubusercontent.com/79616664/140500862-e577e93a-841d-4e9c-86c5-8bba36b30532.png)

Would be nice to remove pop-out and move the text to bottom of help message
![image](https://user-images.githubusercontent.com/79616664/140501054-85a26179-9309-4ca2-8119-82d9e50fb292.png)
