### ISSUE TITLE
[PE-D2] Define same / different person in UG

### ISSUE THREAD

**Issue by hsiaotingluv** [AY2122S1-CS2103T-W08-4/tp#295]
<img width="1229" alt="Screenshot 2021-11-05 at 7 04 42 PM" src="https://user-images.githubusercontent.com/68311371/140501102-1f98797c-f7c6-4938-96f4-29c97dc689e1.png">

specify that they are different person, not a bug

**Comment by choonyongchan** [comment]
To be added into UG
