### ISSUE TITLE
[PE-D2] Find command error

### ISSUE THREAD

**Issue by hsiaotingluv** [AY2122S1-CS2103T-W08-4/tp#308]
<img width="1015" alt="Screenshot 2021-11-05 at 7 33 45 PM" src="https://user-images.githubusercontent.com/68311371/140504462-71310f8d-ad1b-4de5-8ed3-26a6513418c1.png">

find social handle david shows irrelevant people

**Comment by choonyongchan** [comment]
To test it out on the latest version of Socius
