### ISSUE TITLE
Find Command Description should be standardised

### ISSUE THREAD

**Issue by choonyongchan** [AY2122S1-CS2103T-W08-4/tp#319]
Expected:
![image](https://user-images.githubusercontent.com/43673767/140599389-581eb611-e8f4-46c1-a98a-2817179400bc.png)
Actual:
![image](https://user-images.githubusercontent.com/43673767/140599380-c71c4623-3d85-4421-a6c5-9b16f61305e5.png)
Proposed Solution: Simple edit of FindCommand java file

**Comment by bklimey** [comment]
Hi CY, I changed the format to the latter one because it is not clear in the former format that at least one field is required. Therefore, it may be considered a documentation bug if someone did not input any field and encounter an error message when all the fields are stated to be optional.
